"""create subscription plans table

Revision ID: 1606169dacb5
Revises: cbef04c3c248
Create Date: 2026-08-21 01:01:20.319879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1606169dacb5'
down_revision: Union[str, Sequence[str], None] = 'cbef04c3c248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('data_limit_bytes', sa.BigInteger(), nullable=True),
    sa.Column('max_devices', sa.Integer(), server_default='3', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('data_limit_bytes IS NULL OR data_limit_bytes > 0', name='ck_subscription_plans_data_limit_positive'),
    sa.CheckConstraint('duration_days > 0', name='ck_subscription_plans_duration_positive'),
    sa.CheckConstraint('max_devices > 0', name='ck_subscription_plans_devices_positive'),
    sa.CheckConstraint('price_minor_units >= 0', name='ck_subscription_plans_price_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
