"""add data usage records table

Revision ID: 4fb0d8157580
Revises: 84683930bed3
Create Date: 2026-08-21 18:20:55.404894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb0d8157580'
down_revision: Union[str, Sequence[str], None] = '84683930bed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('bytes_used', sa.BigInteger(), nullable=False),
    sa.Column('record_type', sa.String(length=20), server_default='total', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("record_type IN ('upload', 'download', 'total')", name='ck_data_usage_record_type_valid'),
    sa.CheckConstraint('bytes_used > 0', name='ck_data_usage_bytes_positive'),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_usage_records_subscription_id'), 'data_usage_records', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_data_usage_records_user_id'), 'data_usage_records', ['user_id'], unique=False)
    op.create_index('ix_data_usage_subscription_created', 'data_usage_records', ['subscription_id', 'created_at'], unique=False)
    op.create_index('ix_data_usage_user_created', 'data_usage_records', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_usage_user_created', table_name='data_usage_records')
    op.drop_index('ix_data_usage_subscription_created', table_name='data_usage_records')
    op.drop_index(op.f('ix_data_usage_records_user_id'), table_name='data_usage_records')
    op.drop_index(op.f('ix_data_usage_records_subscription_id'), table_name='data_usage_records')
    op.drop_table('data_usage_records')
    # ### end Alembic commands ###
